### PR TITLE
Adding Machine tag to scitos_state_publisher.launch

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by cburbridge** [comment]
I guess this wont change anything if no machine argument is given? The existing way of launching everything without machine things will work without ssh?

**Comment by Jailander** [comment]
yes it does, but I am double checking everything because I found some funny effects on linda don't merge yet please, it may not be related

**Comment by Jailander** [comment]
btw tested and working

**Comment by Jailander** [comment]
I will merge it

**Pull request merged**
